import AppKit
import Observation

@MainActor
@Observable
final class ClipboardHistory {
    enum Kind: Equatable {
        case text
        case link
        case image
        case files
    }

    struct Item: Identifiable, Equatable {
        let id = UUID()
        let kind: Kind
        let text: String
        let image: NSImage?
        let imageData: Data?
        let files: [URL]
        let sourceBundleID: String?
        let date: Date

        static func == (lhs: Item, rhs: Item) -> Bool {
            lhs.id == rhs.id
        }

        func matches(_ other: Item) -> Bool {
            kind == other.kind && text == other.text && files == other.files && imageData == other.imageData
        }
    }

    enum Access: Equatable {
        case off
        case active
        case needsAlwaysAllow
        case denied
    }

    static let enabledKey = "clipboardHistory"
    private static let limit = 40
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
        "Pasteboard generator type",
    ]

    private(set) var items: [Item] = []
    private(set) var access = Access.off
    private(set) var copiedID: Item.ID?

    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var lastChange = NSPasteboard.general.changeCount
    @ObservationIgnored private var ownChange: Int?

    var isEnabled: Bool {
        UserDefaults.standard.bool(forKey: Self.enabledKey)
    }

    func start() {
        guard isEnabled else {
            access = .off
            return
        }
        refreshAccess()
        guard timer == nil else { return }
        lastChange = NSPasteboard.general.changeCount
        timer = Timer.scheduledTimer(withTimeInterval: 0.5, repeats: true) { [weak self] _ in
            MainActor.assumeIsolated { self?.poll() }
        }
        timer?.tolerance = 0.2
    }

    func syncWithPreference() {
        if isEnabled, timer == nil {
            enable()
        } else if !isEnabled, timer != nil {
            disable()
        }
    }

    func enable() {
        UserDefaults.standard.set(true, forKey: Self.enabledKey)
        start()
        if NSPasteboard.general.accessBehavior == .default {
            capture()
            refreshAccess()
        }
    }

    func disable() {
        UserDefaults.standard.set(false, forKey: Self.enabledKey)
        timer?.invalidate()
        timer = nil
        items.removeAll()
        access = .off
    }

    func refreshAccess() {
        guard isEnabled else {
            access = .off
            return
        }
        switch NSPasteboard.general.accessBehavior {
        case .alwaysDeny: access = .denied
        case .ask: access = .needsAlwaysAllow
        default: access = .active
        }
    }

    func copy(_ item: Item) {
        let board = NSPasteboard.general
        board.clearContents()
        switch item.kind {
        case .text, .link:
            board.setString(item.text, forType: .string)
        case .image:
            if let data = item.imageData {
                board.setData(data, forType: .png)
            }
        case .files:
            board.writeObjects(item.files as [NSURL])
        }
        ownChange = board.changeCount
        lastChange = board.changeCount
        if let index = items.firstIndex(of: item) {
            items.insert(items.remove(at: index), at: 0)
        }
        copiedID = item.id
        Task { [weak self] in
            try? await Task.sleep(for: .seconds(1.4))
            if self?.copiedID == item.id { self?.copiedID = nil }
        }
    }

    func remove(_ item: Item) {
        items.removeAll { $0 == item }
    }

    func clear() {
        items.removeAll()
    }

    func openSettings() {
        if let url = URL(string: "x-apple.systempreferences:com.apple.preference.security") {
            NSWorkspace.shared.open(url)
        }
    }

    private func poll() {
        let board = NSPasteboard.general
        guard board.changeCount != lastChange else { return }
        lastChange = board.changeCount
        if ownChange == board.changeCount { return }
        refreshAccess()
        guard access == .active else { return }
        capture()
    }

    private func capture() {
        let board = NSPasteboard.general
        let types = Set((board.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.privateTypes) else { return }
        let source = NSWorkspace.shared.frontmostApplication?.bundleIdentifier
        var item: Item?
        if let urls = board.readObjects(forClasses: [NSURL.self], options: [.urlReadingFileURLsOnly: true]) as? [URL], !urls.isEmpty {
            item = Item(kind: .files, text: urls.map(\.lastPathComponent).joined(separator: ", "), image: nil, imageData: nil, files: urls, sourceBundleID: source, date: .now)
        } else if let data = board.data(forType: .png) ?? board.data(forType: .tiff), data.count < 12_000_000, let image = NSImage(data: data) {
            let png = NSBitmapImageRep(data: data)?.representation(using: .png, properties: [:]) ?? data
            item = Item(kind: .image, text: "Image", image: image, imageData: png, files: [], sourceBundleID: source, date: .now)
        } else if let string = board.string(forType: .string) {
            let trimmed = string.trimmingCharacters(in: .whitespacesAndNewlines)
            guard !trimmed.isEmpty, string.count < 200_000 else { return }
            let isLink = URL(string: trimmed).map { ["http", "https"].contains($0.scheme?.lowercased() ?? "") } ?? false
            item = Item(kind: isLink ? .link : .text, text: string, image: nil, imageData: nil, files: [], sourceBundleID: source, date: .now)
        }
        guard let item else { return }
        items.removeAll { $0.matches(item) }
        items.insert(item, at: 0)
        if items.count > Self.limit {
            items.removeLast(items.count - Self.limit)
        }
    }
}
